### ISSUE TITLE
staticPageState

### ISSUE THREAD

**Issue by lifeiscontent** [iansinnott/react-static-webpack-plugin#22]
@iansinnott what do you think about having a bit of middleware that you could call in a component constructor?

for building out a proper static site that has meta data and what not, I feel like that could get messy really quick.

so what if we exposed an api for something like this?

``` js
import { setStaticPageState } from 'react-static-webpack-plugin';
class Home extends Component {
  constructor() {
    setStaticPageState({
       title: 'foo',
       description: 'bar',
       locale: this.props.route.locale,
       favicon: require('./favicon.ico'), // this might live further up but could be set with the same function
    });
  }
}
```

and then in the template.js provide something like

``` jsx
const Html = (props, pageState) => (
    <html lang={pageState.locale}>
      <head>
        <meta charSet='utf-8' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <title>{pageState.title}</title>
        {pageState.favicon ? <link rel='shortcut icon' href={pageState.favicon} /> : null}
        {pageState.stylesheet ? <link rel='stylesheet' href={pageState.stylesheet} /> : null}
      </head>
      <body>
        <div id='root' dangerouslySetInnerHTML={{ __html: props.body }} />
        <script src={pageState.bundle} />
      </body>
    </html>
)
```

the only problem that is left that I want to solve for this architecture is being able to pass through an asset-hash for the bundle identifier.

**Comment by lifeiscontent** [comment]
Just to give you another look, this is what I have so far that is working outside of this plugin on the server side.

``` jsx
import React, { Component } from 'react';
import { pageState, isServer } from '../../utils';

class PostsIndex extends Component {
  constructor(props) {
    super(props);
    this.state = { isLoading: true };
    if (isServer()) {
      pageState({ title: 'foobar' });
    }
    // console.log(props);
  }
  componentDidMount() {
    this.setState({ isLoading: false }); // set state when browser evaluates JS
  }
  render() {
    return (
      <div>
        {this.state.isLoading ? 'loading' : 'loaded'}
      </div>
    );
  }
}

export default PostsIndex;
```

**Comment by iansinnott** [comment]
Love the idea. 

I think the API doesn't make it too clear exactly what is happening though. I.e. it looks like you're calling a method in the constructor that has some side effect, but it's not clear what that side effect is.

This would provide a huge amount of needed flexibility to the library. My only concern would be the API used to achieve what we want. What about an instance property rather than a function with side effects?

```js
import { setStaticPageState } from 'react-static-webpack-plugin';
class Home extends Component {
  constructor(props) {
    super(props);
    this.staticPageProps = {
       title: 'foo',
       description: 'bar',
       locale: props.route.locale,
       favicon: require('./favicon.ico'), // this might live further up but could be set with the same function
    };
  }
}
```

The reason I want to think critically about the API is that this project now has two somewhat conflicting goals:

1. Allow users to build static sites using **just** React + React Router. I.e. no additional knowledge is needed
2. Be flexible enough to allow users to control the rendering of their components as static pages

So I'd like to limit the API while _also_ providing enough flexibility for people to customize the rendering. I'm not sure what the best approach is.

Some other options to consider:

* A static method on the component. Would not have access to `this.props` but we might be able to pass in any relevant data within the webpack plugin
* A method on the `<Route />` component. We might even be able to hook into existing RR hooks such as `onEnter`.

**Comment by lifeiscontent** [comment]
@iansinnott Yeah, I'm okay with either, just as long as we're not throwing a bunch of state onto a RR route, feel free to share your opinions on this but the main benefits I see using a contract like this is because the constructor is where you setup the component, and since these components are specific to being the main component to create the pages I think it illustrates a clear path of how the data will be consumed by react-static-webpack-plugin while also having the flexibility of using route params or something like redux, or not using any of them at all.
