### ISSUE TITLE
doesn't work with react-slick

### ISSUE THREAD

**Issue by mqklin** [iansinnott/react-static-webpack-plugin#38]
[Demo](https://github.com/mqklin/react-static-webpack-plugin-react-slick-error)

I use [react-slick](https://github.com/akiran/react-slick) in my project. When I try to apply `react-static-webpack-plugin`, webpack throws the error: `Error: Error: matchMedia not present, legacy browsers require a polyfill`.

I found [this](https://github.com/akiran/react-slick/issues/472#issuecomment-248258789). I tried to include polyfill in the `webpack.config.js`:
```
global.matchMedia = {
  matches: false,
  addListener: () => {},
  removeListener: () => {},
};
```
but nothing changed.

Now I import `react-slick` through `require.ensure` as a workaround, but I want to `import` it during bundle as a normal module.

How can I fix this error?

p.s. sorry for my poor english

**Comment by iansinnott** [comment]
I'm not sure what is causing react-slick to fail, however, i can tell you why adding to the global scope didn't work: The source code for your app is run in a [Node VM](https://nodejs.org/api/vm.html) so it gets its own global context and I stub out everything you would normally find in the browser using JSDOM.

My guess is that for some reason JSDOM isn't including `matchMedia` for some reason. 

Check out this issue https://github.com/akiran/react-slick/issues/523. My guess is that the issue is not related to the static site plugin. Also be sure you are running the latest version of this plugin.

Feel free to reopen if you determine that this plugin is the root cause of the error.

**Comment by mqklin** [comment]
I put the polyfill [in all possible places](https://github.com/mqklin/react-static-webpack-plugin-react-slick-error/commit/ef548c5e4d211213b53dcd28509d1a55ddf2421f) and nothing changed :-(
@akiran can you see please?

**Comment by iansinnott** [comment]
Did you use `window` instead of `global` as the example shows?

**Comment by mqklin** [comment]
Yes, you can see it from my comment, i attached a link. I put this code in all possible files and even in `script` tag inside `template.js` before `<script src="app.js"`. Also i put [paulirish's polyfill](https://github.com/paulirish/matchMedia.js/) inside `webpack.config` before all enitries, but it didn't help.
I think i will change `react-slick`to some other carousel.

**Comment by mqklin** [comment]
The error throws from here: `https://github.com/WickyNilliams/enquire.js/blob/master/src/MediaQueryDispatch.js#L9`
