### ISSUE TITLE
Multiples bundles output by route and folder

### ISSUE THREAD

**Issue by paulo101977** [iansinnott/react-static-webpack-plugin#90]
Actually this is not a problem, but rather a suggestion for improvement. For example, for each route and folder generated, there could be one bundle per folder. That is, the main bundle would not be gigantic and each route would have its own bundle, minimizing page load time.

**Comment by iansinnott** [comment]
Yeah, that makes a lot of sense. I'm not sure it's the right fit for this project though. I would welcome a PR.

Have you tried Gatsby? It handles bundle splitting for you as you suggest: https://github.com/gatsbyjs/gatsby

I'm going to close this for now since I think gatsby would solve your use case, but we can definitely reopen if needed.
